#!/usr/bin/python
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'zd.settings'
import django
from zambia.models import Config
from zambia.con_settings import *
from zd.settings import *
django.setup()

i = DATABASES['default']
hostname = i.get('HOST', 'localhost') 
if hostname == '':
    hostname = 'localhost'
print """<?php
// automatically generated by create-db-name on """ + datetime.datetime.now().isoformat() + '''
define("DBHOSTNAME", "''' + hostname + '''"); // Name of the host that the database server runs on.
define("DBUSERID", "''' + i['USER'] + '''"); // User to connect to the dabase server as.
define("DBPASSWORD", "''' + i['PASSWORD'] + '''"); // Password to connect to the database server with.
define("DBDB", "''' + i['NAME'] + '''"); // Database to use.
'''

for i in ('CON_START_DATIM',):
    c = get_con_config(i)
    print 'define("' + i + '", "' + c.isoformat().replace('T',' ') + '"); // ' + Config.objects.get(config=i).description

for i in ('CON_NAME', 'ADMIN_EMAIL', 'BRAINSTORM_EMAIL', 'PROGRAM_EMAIL', 'REG_EMAIL', 'FIRST_DAY_START_TIME', 'OTHER_DAY_START_TIME', 'OTHER_DAY_STOP_TIME', 'LAST_DAY_STOP_TIME', 'STANDARD_BLOCK_LENGTH', 'DEFAULT_DURATION', 'SMTP_ADDRESS', 'SWIFT_DIRECTORY', 'SECOND_LANG', 'SECOND_TITLE_CAPTION', 'SECOND_DESCRIPTION_CAPTION', 'SECOND_BIOGRAPHY_CAPTION', 'BASESESSIONDIR'):
    c = get_con_config(i)
    print 'define("' + i + '", "' + c + '"); // ' + Config.objects.get(config=i).description

for i in ('CON_NUM_DAYS', 'DAY_CUTOFF_HOUR', 'PREF_TTL_SESNS_LMT', 'PREF_DLY_SESNS_LMT', 'AVAILABILITY_ROWS', 'MAX_BIO_LEN'):
    c = get_con_config(i)
    print 'define("' + i + '", ' + repr(c) + ' ); // ' + Config.objects.get(config=i).description

for i in ('DURATION_IN_MINUTES', 'MY_AVAIL_KIDS', 'ENABLE_SHARE_EMAIL_QUESTION', 'ENABLE_BESTWAY_QUESTION', 'BILINGUAL', 'SHOW_BRAINSTORM_LOGIN_HINT'):
    c = get_con_config(i)
    print 'define("' + i + '", ' + repr(c) + ' ); // ' + Config.objects.get(config=i).description

print """global $daymap;
$daymap = array ('long' => array(1 => "Thursday", 2 => "Friday", 3 => "Saturday", 4 => "Sunday", 5 => "Monday"),
    'short' => array(1 => 'Thu', 2 => 'Fri', 3 => 'Sat', 4 => 'Sun', 5 => 'Mon'));
define("stripfancy_from",""); //db & html now is utf8, so supports many characters.  Define these two strings
//				if you need some characters not to be used.  "from" and "to" should be equal length
//				strings.  Any character matched in "from" will be replaced by corresponding character
//				in "to".
define("stripfancy_to","");
?>"""
