#!/usr/bin/perl -w

use strict;

my $tmp_index_line;
my @indicies;
my %indexcount;
my %reportmap;
my $index;
my $insertline="INSERT INTO `GroupFlow` (reportid, gflowname, gfloworder) VALUES ";

my $host;
my $dbname;
my $user;
my $pass;

open (DBNAME, "../Local/db_name.php") || die "Can't open db_name.php file: $!\n";
while (<DBNAME>){
    if ($_ =~ /DBHOSTNAME".*"(.*)"/) {$host=$1;}
    if ($_ =~ /DBDB".*"(.*)"/) {$dbname=$1;}
    if ($_ =~ /DBUSERID".*"(.*)"/) {$user=$1;}
    if ($_ =~ /DBPASSWORD".*"(.*)"/) {$pass=$1;}
}
close(DBNAME);

# Get the reportid to reportname mapping as generated by:
my $query="echo \"SELECT reportid,reportname FROM Reports;\" | mysql -h".$host." -u".$user." -p".$pass." -B ".$dbname;
open (LISTQUERY, "$query |") || warn "Can't open query: $!\n";
while (<LISTQUERY>) {
    if ($_ =~ /^(\d*)\s*(\w*)$/) {
	$reportmap{$2 . "report.php"}=$1;
    }
}
close(LISTQUERY);

# Generate the list of files to be searched
opendir(WORKDIR, "../webpages") || warn "Can't open ../webpages: $!\n";
my @files = grep(/report.php/, readdir WORKDIR);
closedir(WORKDIR);
@files = grep (!/^genreport.php/, @files);

# Walk the files, and put the indicies in the appropriate mappings.
foreach my $filename (@files) {
    $tmp_index_line="";
    @indicies=();
    open (WORKFILE, $filename) || warn "Can't open $filename: $!\n";
    while (<WORKFILE>) {
	if ($_ =~ /\$indicies="(.*)";/) {$tmp_index_line=$1;}
    }
    close(WORKFILE);
    @indicies=split(/, /,$tmp_index_line);
    foreach $index (@indicies) {
	if ($index =~ /CSV/) {next;}
	$index=~s/WANTS=1//;
        $index=~s/(\w+)/\u\L$1/g;
        $indexcount{$index}++;
	$insertline .= "(".$reportmap{$filename}.",'".$index."',".$indexcount{$index}."),";
    }
}

#Output the insert line
chop $insertline;
$insertline.=";";
print "$insertline\n";
