<?php
  $title="REPORT_TITLE";
  require_once('db_functions.php');
  require_once('StaffHeader.php');
  require_once('StaffFooter.php');
  require_once('StaffCommonCode.php');
  staff_header($title);
?>
<P>REPORT_DESCRIPTION
