#!/bin/sh

mkdir -p /home/trg/Arisia08 

/usr/bin/mysql --password='arisia' arisia -e "\. /home/trg/bin/export_program_participants_arisia08.sql"  > /home/trg/Arisia08/latest_congo

/usr/bin/scp -P 2600 /home/trg/Arisia08/latest_congo two-step.netbusters.com:Arisia08/latest_congo
