<?php
define("DBHOSTNAME","localhost");
define("DBUSERID","olszowka");
define("DBPASSWORD","");
define("DBDB","olszowkadev");
define("CON_NAME","PeterCon");
define("BRAINSTORM_EMAIL","brain@somewhere.net");
define("PROGRAM_EMAIL","nobody@somewhere.net");
define("REG_EMAIL","noone@somewhere.net");
define("stripfancy_from","ÀÁÂÃÄÅÆÇÈÉÊË");
define("stripfancy_to","AAAAAAECEEEE");
?>
