## This script updates CustomText table to add two new entries.
##
##  Created by Peter Olszowka on June 27, 2026
##  Copyright (c) 2026 by Peter Olszowka. All rights reserved. See copyright document for more details.
##
INSERT IGNORE INTO `CustomText`
    (page, tag, textcontents, active, html_block_level)
    VALUES
    ('My Profile','biography_note','<p>This is the text that people will read about you in our printed and online guides. Please be sure to review and proof it accordingly, edit out any typographic characters that appear if you paste a bio that displays them in our database system, and make updates as necessary. Your bio will be published as written by you in this section, subject to formatting cleanup.</p>',0,1),
    ('My Profile','registration_data','<p>Please confirm your contact information. If it is not correct, please email <a href=\"mailto:$PROGRAM_EMAIL$\" target=\"_blank\" rel=\"noopener\">$PROGRAM_EMAIL$</a> to update your contact info. This data is downloaded periodically from the registration database, and should be correct once they have updated it in the registration system.</p>',0,1),
    ('My Profile','policy_block_at_top','',0,1),
    ('My Availability','note_before_time_slots','<p>For each day you will be attending $CON_NAME$, please indicate the times when you will be available as a program panelist. Entering a single time for the whole con is fine. Splitting a day into multiple time slots is also fine. Change all items in a row to blank to delete the row. If you schedule yourself as unavailable across part of a panel timeblock we will not schedule you for any panels in that timeblock.  Remember that times are in our local timezone.</p>',0,1),
    ('My Availability','note_after_time_slots','<p>Thank you for sharing your availability with us. Please know that we are always looking for program participants who are available during the evening hours.</p>\n<p>You may return to this page to change your availability as needed</p>',0,1),
    ('Note to All Panelists 1','all_panelists_1','',0,1),
    ('Note to all Panelists 2','all_panelists_2','',0,1),
    ('Data Retention Consent','consent','<div><p>We collect personal data to allow us to schedule your programming items, allow other participants to contact you (with your explicit consent), and perform internal administrative tasks. We do not share personal data with other conventions or organizations.</p>\n<p>Public data, such as your biography, photo, and socials, will be published in our printed program guide and online schedule.</p>\n<p>Without your consent we are unable to have you as a program participant.</p></div>',0,1),
    ('My Photo','photo_note','<p>Note: Photos should be of type JPEG (.jpg) or PNG (.png), 1 MB or less in size and should be about 800x800. If you need to optimize your photo''s file size we suggest "Save For Web".</p>\n<p>After uploading, you will be able to crop and rotate the image. To upload a photo, either drag the file to the upload photo area or click the upload photo button to use a file picker to select the file to upload.</p>\n<p>All photos uploaded will be reviewed for approval—a default placeholder stock image will appear prior to approval. The approved photo will be available for use in publications, on-line guides, and marketing materials. If you already have an approved photo, any new photo uploaded will be added to the review queue and it will replace the approved photo once reviewed and accepted.</p>',0,1),
    ('Participant Survey','survey_displayonly','<p>Note: Some questions may no longer allow you to enter/change their answers. The time has passed for when you can change them and they have been changed from answerable to display only.</p>\n<p>If you need to have a display only answer changed, please reach out to programming at the email address below.</p>',0,1),
    ('Participant View','part_overview','',0,1),
    ('Staff Overview','staff_overview','<p>Please note the tabs above. One of them will take you to your participant view. Another will allow you to manage Sessions. Note that Sessions is the generic term Zambia uses for anything it can schedule, e.g. Panels, Events, Readings, etc.</p>\n<p>The general flow of sessions over time is:</p>\n<dl>\n<dt>Brainstorm</dt>\n<dd>If $CON_NAME$ is using the brainstorm functionality, these are sessions created by non-staff members which haven''t yet been edited by a staff member.</dd>\n<dt>Edit Me</dt>\n<dd>New session idea that a staff member entered. An idea entered by a brainstorm user that is non-offensive and the least bit feasible should be moved to this status. These are still rough and may well have issues. There still could be duplicates.</dd>\n<dt>Vetted</dt>\n<dd>A real session that we''d like to see happen. At this point the language should be fairly close to final in the description. Proofreading should have happened. More fields are required at this point. This is the minimal status that participants are allowed to sign up for. Avoid duplicates, but many of these still will not happen for various reasons.</dd>\n<dt>Assigned</dt>\n<dd>Session has participants assigned to it.</dd>\n<dt>Scheduled</dt>\n<dd>Session is in the schedule (don''t set this by hand as Zambia actually sets this for you when you schedule it in a room!) The language needs to match what you want to see <strong>published</strong>.</dd>\n</dl>\n<p>There are 3 other statuses that a session can have:</p>\n<dl>\n<dt>Dropped</dt>\n<dd>This item is no longer under consideration and is unlikely even to be mined for future ideas.</dd>\n<dt>Duplicate</dt>\n<dd>Might have been a good session, but was too close or identical to another one.</dd>\n<dt>Cancelled</dt>\n<dd>Over all a good idea, but it isn''t going to happen this year. Generally used later in the programming process. You should probably still say why it was cancelled in the "Notes for Program Committee" field. This is a category we can mine for ideas in future years</dd>\n</dl>\n<p>Some details regarding $CON_NAME$":</p>\n<dl class="ms-4">\n<dd>Convention dates: $CON_START_DATE$ - $CON_END_DATE$</dd>\n<dd>Number of days: $CON_NUM_DAYS$</dd>\n</dl>',0,1),
    ('Declined to Invite','declined_particpant','<h3 class="mb-2">Thank you so much for contacting $CON_NAME$.</h3>\n<p>If you are receiving this message, your record in the Zambia system has been closed. A closed record indicates one or more of three things:</p>\n<ol>\n<li>You contacted $CON_NAME$ to let us know that you are unable to participate in the program this year.</li>\n<li>You did not meet a deadline to contact us or provide required information.</li>\n<li>You were not selected to be on the $CON_NAME$ program. We received far more requests to be on program from qualified and amazing people than it is possible to accommodate.</li>\n</ol>\n<p>If you have any questions or if you believe that an error has been made, please contact us at <a href="mailto:$PROGRAM_EMAIL$">$PROGRAM_EMAIL$</a></p>',0,1),
    ('General Interests','panel_types_not_int','Panel types I am not interested in participating in:',0,0),
    ('General Interests','other_role_desc','Description for "Other" Roles:',0,0),
    ('General Interests','roles_checkboxes_label','Roles I\'m willing to take on:',0,0),
    ('General Interests','stuff_id_like_to_run','Workshops or presentations I''d like to run:',0,0),
    ('General Interests','people_want_on_sess_label','People with whom I\'d like to be on a session: (Leave blank for none)',0,0),
    ('General Interests','people_dont_want_label','People with whom I\'d rather not be on a session: (Leave blank for none)',0,0);

INSERT INTO `PatchLog` (patchname) VALUES ('69_custom_text_cleanup.sql');
