#!/bin/sh
# this script takes a file in the below format 
# and generate the mysql to load into zambia: 
# badgeid|badgename|firstname|lastname|phone|email|postaddress1|postaddress2|postcity|poststate|postzip|postcountry|regtype

DATAFILE='foo'

INITIALUSERPASSWD='4cb9c8a8048fd02294477fcb1a41191a'  # aka 'changeme'
# if you want to replace this, you'll need to md5 the string. 
# note that there is a web tool for staff to reset passwords.


IFS='|'
cat foo | while read badgeid badgename firstname lastname phone email postaddress1 postaddress2 postcity poststate postzip postcountry regtype  
do 
  echo "insert into CongoDump set badgeid=\"$badgeid\";"
  echo "update CongoDump set badgename=\"$badgename\", lastname=\"$lastname\", firstname=\"$firstname\", phone=\"$phone\", email=\"$email\", postaddress1=\"$postaddress1\", postaddress2=\"$postaddress2\", postcity=\"$postcity\", poststate=\"$poststate\", postzip=\"$postzip\", postcountry=\"$postcountry\", regtype=\"$regtype\" where badgeid=\"$badgeid\";"
  echo "insert into Participants set badgeid=\"$badgeid\", password=\"$INITIALUSERPASSWD\";"

# permroleid of 1 means administrator, 2 means staff, 3 means participant, 4 means brainstorm... 
# you'll want to pick and choose
  echo "insert into UserHasPermissionRole set badgeid=\"$badgeid\", permroleid=1;"
  echo "insert into UserHasPermissionRole set badgeid=\"$badgeid\", permroleid=2;"
  echo "insert into UserHasPermissionRole set badgeid=\"$badgeid\", permroleid=3;"
done

exit 
# ok, the following 2 lines can be put directly into 
#the DATAFILE and they will work. 
1|staff1|First|Staff|781-555-1212|someone@somewhere.com|123 First Street||Arlington|MA|02474|USA|staffcomp
2|part1|First|Participant|617-555-1212|someoneelse@somewhereelse.com|321 Fifth Street|Apt. 1|Boston|MA|02234|USA|partcomp
